//
//  RocketDetailPresenter.swift
//  Star
//
//  Created by Alireza Namazi on 2/6/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//


import UIKit

protocol RocketDetailPresentationLogic
{
    func presentDetail(response: RocketDetail.Roket.Response)
}

class RocketDetailPresenter: RocketDetailPresentationLogic
{
    weak var viewController: RocketDetailDisplayLogic?
    
    // MARK: Do something
    
    func presentDetail(response: RocketDetail.Roket.Response)
    {
        let detail = response.rocket
        let model = RocketDetail.Roket.ViewModel.DisplatRocket(id: detail.id ?? "", name: detail.name ?? "", description: detail.description ?? "", flickr_images: detail.flickrImages ?? [], country: detail.country ?? "", company: detail.company ?? "")
        let viewModel = RocketDetail.Roket.ViewModel(displayRocket: model)
        viewController?.displayDetail(viewModel: viewModel)
    }
}
